image:
  repository: ghcr.io/mintplex-labs/anything-llm
  pullPolicy: IfNotPresent
  tag: latest@sha256:dcae5dddbbf10e983004601e726648f178d5a39011608fb3b072e4abacd5f264
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    capabilities:
      add:
        - SYS_ADMIN

service:
  main:
    ports:
      main:
        protocol: http
        port: 3001

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            STORAGE_DIR: "{{.Values.persistence.storage.mountPath }}"
            # forces users to use ingress if https is needed.
            # keep false.
            ENABLE_HTTPS: false

persistence:
  storage:
    enabled: true
    mountPath: "/app/server/storage"
  hotdir:
    enabled: true
    mountPath: "/app/collector/hotdir"
  outputs:
    enabled: true
    mountPath: "/app/collector/outputs"

portal:
  open:
    enabled: true
